name: TDD_test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y g++ cmake libboost-all-dev

      - name: Build dependencies
        run: ./build_dependences.sh

      - name: Run tests
        run: ./test.sh